### ISSUE TITLE
please add community guidelines

### ISSUE THREAD

**Issue by mikapfl** [fgjorup/Reel#8]
Hi,

for JOSS acceptance, Reel needs "clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support". So, please state if and how you accept third-party contributions / patches, briefly describe how to report issues and if there are channels to seek support when using Reel.

Cheers,

Mika

**Comment by fgjorup** [comment]
Hi Mika
I've added a few lines about contributing/contacting in the readme.md
